.PHONY: all stage
all: stage

stage: LatitudeSettings/build/Release-iphoneos/LatitudeSettings.app/LatitudeSettings
	cp -R LatitudeSettings/build/Release-iphoneos/LatitudeSettings.app stage/Applications/
	chmod a+x stage/Applications/LatitudeSettings.app/LatitudeSettings


